package Constants

WORLD_SIZE :: 100.0

PLAYER_MAX_SPEED :: 100.0
PLAYER_ACCELERATION :: 10.0
PLAYER_LASER_RELOAD_TIME :: 0.5

LASER_SHOT_TTL :: 10.0
LASER_SHOT_VELOCITY :: 10.0

INITIAL_ASTEROID_COUNT :: 5
ASTEROID_INCREASE_TIME :: 10.0
ASTEROID_COLLISION_SCALE :: 0.55

MAX_DRAW_ITERATIONS :: 2